title: Isaac Overcast
description: Investigating biodiversity across spatial, temporal, and taxonomic scales
show_downloads: true

baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://isaacovercast.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: isaacovercast
image: /thumbnail-jumbo.png
twitter:
  username: isaacovercast

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'research', 'contact']
